pipeline {
    agent any

    tools {
        maven "MAVEN_HOME"
    }

    stages {
        stage('Get Latest Code') {
            steps {
                echo 'Get Latest Code'
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mmukul/simple-app-devopscicd-demo']]])
            }
        }
		stage('Clean the Workspace') {
            steps {
                echo 'Clean the Workspace'
                sh "mvn clean"
            }
        }
		stage('Compile') {
            steps {
                echo 'Compile'
                sh "mvn compile"
            }
        }
		stage('Test') {
            steps {
                echo 'Test'
                sh "mvn test"
				
            }
        }
		stage('Package') {
            steps {
                echo 'Package the Solution'
                sh "mvn package"
            }
        }
		
		// Delivery stage
		stage('Deploy to PROD') {
            steps {
                input 'Do you want to continue deployment to PROD?'
		echo 'Deploy to PROD'		
            }
        }	
    }
}
