#!/bin/bash

### Run on Jenkins Master and Jenkins Slave using CLI on Linux Terminal ###

sudo yum install -y git java-1.8.0-openjdk-devel
wget http://mirrors.ibiblio.org/apache/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz -P /opt
cd /opt

tar xzvf apache-maven-3.9.9-bin.tar.gz

sudo ln -s /opt/apache-maven-3.9.9 /opt/maven

cat <<EOF | sudo tee /etc/profile.d/maven.sh
export JAVA_HOME=/usr/lib/jvm/jre-openjdk
export MAVEN_HOME=/opt/maven
export PATH=${MAVEN_HOME}/bin:${PATH}
EOF

sudo chmod +x /etc/profile.d/maven.sh

source /etc/profile.d/maven.sh
