pipeline {
    agent any

    // Jenkins Pipeline
    stages {
        stage ('Initialize Environment') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "MAVEN_HOME = ${MAVEN_HOME}"
                    ''' 
            }
        }

        stages {
        stage('Get Latest Code') {
            steps {
                echo 'Get Latest Code'
                git 'https://github.com/mmukul/Jenkins_Sample_Java_Project.git'
            }
        }
		stage('Clean the Workspace') {
            steps {
                echo 'Clean the Workspace'
                sh "mvn clean"
            }
        }
		stage('Compile') {
            steps {
                echo 'Compile'
                sh "mvn compile"
            }
        }
		stage('Test') {
            steps {
                echo 'Test'
                sh "mvn test"
				
            }
        }
		stage('Package') {
            steps {
                echo 'Package the Solution'
                sh "mvn package"
            }
        }
		
		// Delivery stage
		stage('Deploy to PROD') {
            steps {
                input 'Do you want to continue deployment to PROD?'
				echo 'Deploy to PROD'		
            }
        }	
    }
}
